default: &default
  adapter: postgresql
  encoding: unicode  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: mind_app_development
  username: postgres
  password: 1234
  
test:
  <<: *default
  database: mind_app_test
  username: postgres
  password: 1234

production:
  <<: *default
  database: mind_app_production
  username: postgres
  password: 1234
  # username: mind_app
  # password: <%= ENV['MIND_APP_DATABASE_PASSWORD'] %>
